#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.21
#  in conjunction with Tcl version 8.6
#    Mar 05, 2019 02:01:30 AM IST  platform: Linux

import sys
import pymysql

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import add_book_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    add_book_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (root)
    destroy_Toplevel1()
    add_book_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font10 = "-family {DejaVu Sans} -size 15"

        top.geometry("1000x700+250+74")
        top.title("Library Management System - IIT Jammu")
        
        self.Labelframe1 = tk.LabelFrame(top)
        self.Labelframe1.place(relx=0.12, rely=0.129, relheight=0.621
                , relwidth=0.71)
        self.Labelframe1.configure(relief='groove')
        self.Labelframe1.configure(font=font10)
        self.Labelframe1.configure(text='''Add a new book''')
        self.Labelframe1.configure(width=710)

        self.Label1 = tk.Label(self.Labelframe1)
        self.Label1.place(relx=0.155, rely=0.138, height=50, width=70
                , bordermode='ignore')
        self.Label1.configure(font=font10)
        self.Label1.configure(text='''Title''')
        self.Label1.configure(width=79)

        self.Label2 = tk.Label(self.Labelframe1)
        self.Label2.place(relx=0.155, rely=0.253, height=50, width=70
                , bordermode='ignore')
        self.Label2.configure(cursor="fleur")
        self.Label2.configure(font=font10)
        self.Label2.configure(text='''Year''')
        self.Label2.configure(width=59)

        self.Label3 = tk.Label(self.Labelframe1)
        self.Label3.place(relx=0.155, rely=0.368, height=50, width=70
                , bordermode='ignore')
        self.Label3.configure(font=font10)
        self.Label3.configure(text='''ISBN''')

        self.Label4 = tk.Label(self.Labelframe1)
        self.Label4.place(relx=0.155, rely=0.483, height=50, width=70
                , bordermode='ignore')
        self.Label4.configure(font=font10)
        self.Label4.configure(text='''Pages''')

        self.Label5 = tk.Label(self.Labelframe1)
        self.Label5.place(relx=0.141, rely=0.598, height=50, width=150
                , bordermode='ignore')
        self.Label5.configure(font=font10)
        self.Label5.configure(text='''Publisher ID''')

        self.Entry1 = tk.Entry(self.Labelframe1)
        self.Entry1.place(relx=0.352, rely=0.161, height=25, relwidth=0.282
                , bordermode='ignore')
        self.Entry1.configure(background="white")
        self.Entry1.configure(font="TkFixedFont")

        self.Entry2 = tk.Entry(self.Labelframe1)
        self.Entry2.place(relx=0.352, rely=0.276, height=25, relwidth=0.282
                , bordermode='ignore')
        self.Entry2.configure(background="white")
        self.Entry2.configure(font="TkFixedFont")

        self.Entry3 = tk.Entry(self.Labelframe1)
        self.Entry3.place(relx=0.352, rely=0.391, height=25, relwidth=0.282
                , bordermode='ignore')
        self.Entry3.configure(background="white")
        self.Entry3.configure(font="TkFixedFont")

        self.Entry4 = tk.Entry(self.Labelframe1)
        self.Entry4.place(relx=0.352, rely=0.506, height=25, relwidth=0.282
                , bordermode='ignore')
        self.Entry4.configure(background="white")
        self.Entry4.configure(font="TkFixedFont")

        self.Entry5 = tk.Entry(self.Labelframe1)
        self.Entry5.place(relx=0.352, rely=0.621, height=25, relwidth=0.282
                , bordermode='ignore')
        self.Entry5.configure(background="white")
        self.Entry5.configure(font="TkFixedFont")

        self.Button1 = tk.Button(self.Labelframe1)
        self.Button1.place(relx=0.394, rely=0.759, height=41, width=131
                , bordermode='ignore')
        self.Button1.configure(font=font10)
        self.Button1.configure(text='''Add Record''')
        self.Button1.configure(width=131)
        self.Button1.configure(command=self.insert_book)

    # run a mysql query 
    def run_query(self, query, parameters=()):
        db = pymysql.connect("localhost", "admin", "admin", "lms")
        cursor = db.cursor()
        # print(query)
        cursor.execute(query, parameters)
        db.commit()
        query_result = cursor.fetchall()
        return query_result

    def insert_book(self):
        query = "insert into Book(book_id, title, year, isbn, pages, publisher_id) "
        title = self.Entry1.get()
        year = int(self.Entry2.get())
        isbn = self.Entry3.get()
        pages = int(self.Entry4.get())
        publisher_id = int(self.Entry5.get())
        
        # get the book_id
        get_id = "select count(*) from Book;"
        result = self.run_query(get_id)
        book_id = result[0][0] + 1

        query += "values ({0}, \'{1}\', {2}, \'{3}\', {4}, {5});".format(book_id, title, year, isbn, pages, publisher_id)
        self.run_query(query)

if __name__ == '__main__':
    vp_start_gui()





